### ISSUE TITLE
[Bug]: production.ERROR: URI is not valid and cannot be converted into a string {"exception":"[object] (Laminas\\Uri\\Exception\\InvalidUriException(code: 0): URI is not valid and cannot be converted into a string at phar:///Users/user/expose/vendor/laminas/laminas-uri/src/Uri.php:382) 

### ISSUE THREAD

**Issue by filecc** [exposedev/expose#431]
### System architecture

Mac, ARM64 (M1, M2, etc)

### Bug description

What I paid for? 
Everytime I try to open just the homepage I receive this output:

```bash
production.ERROR: URI is not valid and cannot be converted into a string {"exception":"[object] (Laminas\\Uri\\Exception\\InvalidUriException(code: 0): URI is not valid and cannot be converted into a string at phar:///Users/user/expose/vendor/laminas/laminas-uri/src/Uri.php:382)
[stacktrace]
#0 phar:///Users/user/expose/vendor/laminas/laminas-http/src/Header/AbstractLocation.php(103): Laminas\\Uri\\Uri->toString()
#1 phar:///Users/user/expose/vendor/laminas/laminas-http/src/Header/AbstractLocation.php(128): Laminas\\Http\\Header\\AbstractLocation->getUri()
#2 phar:///Users/user/expose/vendor/laminas/laminas-http/src/Headers.php(457): Laminas\\Http\\Header\\AbstractLocation->getFieldValue()
#3 phar:///Users/user/expose/app/Logger/LoggedRequest.php(187): Laminas\\Http\\Headers->toArray()
#4 phar:///Users/user/expose/app/Logger/LoggedRequest.php(47): App\\Logger\\LoggedRequest->getRequestId()
#5 phar:///Users/user/expose/app/Logger/RequestLogger.php(35): App\\Logger\\LoggedRequest->__construct('GET /firebase-m...', Object(Laminas\\Http\\Request))
#6 phar:///Users/user/expose/app/Client/Http/HttpClient.php(52): App\\Logger\\RequestLogger->logRequest('GET /firebase-m...', Object(Laminas\\Http\\Request))
#7 phar:///Users/user/expose/app/Client/ProxyManager.php(81): App\\Client\\Http\\HttpClient->performRequest('GET /firebase-m...', Object(Ratchet\\Client\\WebSocket), Object(stdClass))
#8 phar:///Users/user/expose/app/Client/ProxyManager.php(35): App\\Client\\ProxyManager->performRequest(Object(Ratchet\\Client\\WebSocket), 'GET /firebase-m...', Object(stdClass))
#9 phar:///Users/user/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): App\\Client\\ProxyManager->{closure:{closure:App\\Client\\ProxyManager::createProxy():33}:34}(Object(Ratchet\\RFC6455\\Messaging\\Message), Object(Ratchet\\Client\\WebSocket))
#10 phar:///Users/user/expose/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\\Client\\WebSocket->emit('message', Array)
#11 phar:///Users/user/expose/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\\Client\\WebSocket->{closure:Ratchet\\Client\\WebSocket::__construct():71}(Object(Ratchet\\RFC6455\\Messaging\\Message), Object(Ratchet\\RFC6455\\Messaging\\MessageBuffer))
#12 phar:///Users/user/expose/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\\RFC6455\\Messaging\\MessageBuffer->processData('\\x82~\\x05YGET /fireba...')
#13 phar:///Users/user/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\\RFC6455\\Messaging\\MessageBuffer->onData('\\x82~\\x05YGET /fireba...')
#14 phar:///Users/user/expose/vendor/react/stream/src/Util.php(71): Evenement\\EventEmitter->emit('data', Array)
#15 phar:///Users/user/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\\Stream\\Util::{closure:React\\Stream\\Util::forwardEvents():70}('\\x82~\\x05YGET /fireba...')
#16 phar:///Users/user/expose/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\\EventEmitter->emit('data', Array)
```

Do you know something about this? Make the whole package completely useless. 
Can I get a refund at least? 
It's been already two days!

**Comment by filecc** [comment]
It's been 2 weeks. 
ANY news from you?

**Comment by LiamSystems** [comment]
+1 Same issue for me.

**Comment by ahtinurme** [comment]
Same here. Not every request, but every second :(

**Comment by filecc** [comment]
Not planned?? What than even mean?

**Comment by mpociot** [comment]
This is now fixed in v3 (which will be tagged soon)
